version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - '80:8080'
      - '50000:50000'
    labels:
      kompose.service.type: LoadBalancer
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    labels:
      kompose.service.type: LoadBalancer