version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '80:8080'
      - '50000:50000'
    labels:
      kompose.service.type: LoadBalancer
    volumes:
      - docker:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    labels:
      kompose.service.type: LoadBalancer
volumes:
  jenkins_home:
  docker: