apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        name: jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker
        - mountPath: /var/jenkins_home
          name: jenkins-home
      volumes:
      - name: docker
        persistentVolumeClaim:
          claimName: docker
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home
      initContainers:
      - name: permissionsfix
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - chown 1000:1000 /var/jenkins_home;
        volumeMounts:
        - name: jenkins-home # Or you can replace with any name
          mountPath: /var/jenkins_home # Must match the mount path in the args line
      restartPolicy: Always

status: {}